/**
 * Full list of lists of words we'll be using. The format is the following: [ [], [], [],.. ]
 *     
 * Each list will contain 3 strings.
 * Index 0 will contain the 'spanish' version of the word.
 * Index 1 will contain the 'english' version of the word.
 * Index 2 will contain the 'type' version of the word.
 */
const listWords = [
  ["gato", "cat", "noun"],
  ["perro", "dog", "noun"],
  ["casa", "house", "noun"],
  ["sol", "sun", "noun"],
  ["luna", "moon", "noun"],
  ["rojo", "red", "adjective"],
  ["azul", "blue", "adjective"],
  ["verde", "green", "adjective"],
  ["amarillo", "yellow", "adjective"],
  ["feliz", "happy", "adjective"],
  ["triste", "sad", "adjective"],
  ["rápido", "fast", "adjective"],
  ["lento", "slow", "adjective"],
  ["amigo", "friend", "noun"],
  ["amor", "love", "noun"],
  ["libro", "book", "noun"],
  ["mesa", "table", "noun"],
  ["silla", "chair", "noun"],
  ["playa", "beach", "noun"],
  ["ciudad", "city", "noun"],
  ["montaña", "mountain", "noun"],
  ["jardín", "garden", "noun"],
  ["fuerte", "strong", "adjective"],
  ["débil", "weak", "adjective"],
  ["nuevo", "new", "adjective"],
  ["viejo", "old", "adjective"],
  ["agua", "water", "noun"],
  ["fuego", "fire", "noun"],
  ["aire", "air", "noun"],
  ["tierra", "earth", "noun"],
  ["manzana", "apple", "noun"],
  ["fruta", "fruit", "noun"],
  ["carro", "car", "noun"],
  ["bicicleta", "bicycle", "noun"],
  ["viaje", "trip", "noun"],
  ["trabajo", "work", "noun"],
  ["escuela", "school", "noun"],
  ["estudiante", "student", "noun"],
  ["profesor", "teacher", "noun"],
  ["doctor", "doctor", "noun"],
  ["enfermedad", "illness", "noun"],
  ["dinero", "money", "noun"],
  ["precio", "price", "noun"],
  ["dolor", "pain", "noun"],
  ["sueño", "dream", "noun"],
  ["familia", "family", "noun"],
  ["comida", "food", "noun"],
  ["ropa", "clothing", "noun"],
  ["musica", "music", "noun"],
  ["arte", "art", "noun"],
  ["verano", "summer", "noun"],
  ["invierno", "winter", "noun"],
  ["otoño", "autumn", "noun"],
  ["primavera", "spring", "noun"],
  ["hermano", "brother", "noun"],
  ["hermana", "sister", "noun"],
  ["padre", "father", "noun"],
  ["madre", "mother", "noun"],
  ["hijo", "son", "noun"],
  ["hija", "daughter", "noun"],
  ["canción", "song", "noun"],
  ["pintura", "painting", "noun"],
  ["película", "movie", "noun"],
  ["teléfono", "phone", "noun"],
  ["computadora", "computer", "noun"],
  ["frío", "cold", "adjective"],
  ["caliente", "hot", "adjective"],
  ["lugar", "place", "noun"],
  ["persona", "person", "noun"],
  ["cielo", "sky", "noun"],
  ["nube", "cloud", "noun"],
  ["amable", "kind", "adjective"],
  ["cruel", "cruel", "adjective"],
  ["rápido", "quick", "adjective"],
  ["largo", "long", "adjective"],
  ["corto", "short", "adjective"],
  ["alto", "tall", "adjective"],
  ["bajo", "short", "adjective"],
  ["grande", "big", "adjective"],
  ["pequeño", "small", "adjective"],
  ["cierto", "true", "adjective"],
  ["falso", "false", "adjective"],
  ["hermoso", "beautiful", "adjective"],
  ["feo", "ugly", "adjective"],
  ["rico", "rich", "adjective"],
  ["pobre", "poor", "adjective"],
  ["feliz", "happy", "adjective"],
  ["enojado", "angry", "adjective"],
  ["sorpresa", "surprise", "noun"],
  ["miedo", "fear", "noun"],
  ["sabor", "taste", "noun"],
  ["olor", "smell", "noun"]
]
export default listWords;